### ISSUE TITLE
can this build on healthcareblocks?

### ISSUE THREAD

**Issue by cordoval** [HealthcareBlocks/php-example#1]
is there support for docker-compose?

I was doing it with a Procfile but trying to make it work with Dockerfile, can you please share some info on this?

**Comment by philm** [comment]
Hi Luis, this example repo _can_ be used with Docker Compose. Check out https://docs.docker.com/compose/production/ for learning about how to use Compose in production. 

If you are using the Dokku framework, it recognizes Dockerfiles natively, see
http://dokku.viewdocs.io/dokku~v0.6.5/deployment/methods/dockerfiles/

**Comment by cordoval** [comment]
@philm i know, our project already supports docker-compose

my question is more how to get it working with dokku. Dokku needs a Procfile, so was wondering whether it was supporting docker-compose directly/already.

**Comment by philm** [comment]
@cordoval - Dokku and Docker Compose are mutually exclusive - if you're using one, you don't need the other. With Docker Compose, you will either have a run command (or shell script) in the image to start the process. Environment settings can be in the docker-compose-production.yml or for sensitive values that you don't want in source control, use the docker-compose env file key (https://docs.docker.com/compose/compose-file/#/env-file) and point to a config file sitting on the server.
